// <auto-generated />
namespace GPBH.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update_View_vw_BaoCaoBanTheoKhachHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_View_vw_BaoCaoBanTheoKhachHang));
        
        string IMigrationMetadata.Id
        {
            get { return "202508181349042_Update_View_vw_BaoCaoBanTheoKhachHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
