// <auto-generated />
namespace GPBH.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddSysMenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSysMenu));
        
        string IMigrationMetadata.Id
        {
            get { return "202506011150172_Add-SysMenu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
